"""empty message

Revision ID: 29018c162d13
Revises: 3d2b525baf13
Create Date: 2024-07-23 11:38:13.028983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29018c162d13'
down_revision = '3d2b525baf13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=100), nullable=True))
        batch_op.execute("UPDATE items SET decription='No Description added.'")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
